spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${USERNAME}
    password: ${PASSWORD}
    hikari:
      maximum-pool-size: 4
      connection-init-sql: SET TIME ZONE 'Asia/Seoul'
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

open-api:
  encoding-service-key: ${ENCODING_SERVICE_KEY}

schedule:
  cron: 0 0 12 * * * # 매일 오호 12시
