spring:
  config:
    import: secret.yml
  datasource:
    url: ${DEV.RDB.DATABASE_URL}
    username: ${DEV.RDB.USERNAME}
    password: ${DEV.RDB.PASSWORD}
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true # SQL 포맷팅
        highlight_sql: true # ANSI 코드에 색을 나타낸다
        use_sql_comments: true # SQL 내부에 /* */ 주석 추가

open-api:
  encoding-service-key: ${DEV.OPEN_API.ENCODING_SERVICE_KEY}
  decoding-service-key: ${DEV.OPEN_API.DECODING_SERVICE_KEY}